<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>

    <?php /** @var $block Magento\Company\Block\Company\Management\Add */ ?>

        <form class="form form-add-user" method="post" id="add-user-form" action="<?= $block->escapeUrl($block->getUrl('*/customer/manage')) ?>" data-mage-init='{"validation":{}}'>
            <input type="hidden" name="target_id" />
            <input type="hidden" name="customer_id" />
            <fieldset class="fieldset info">
                <div class="field jobtitle required">
                    <label class="label" for="jobtitle">
                        <span><?= $block->escapeHtml(__('Job Title')) ?></span>
                    </label>
                    <div class="control">
                        <input type="text" name="extension_attributes[company_attributes][job_title]" id="jobtitle" value="" title="<?= $block->escapeHtml(__('Job Title')) ?>" class="input-text" data-validate="{required:true}" maxlength="50">
                    </div>
                </div>
                <div class="field role required">
                    <label class="label" for="jobtitle">
                        <span><?= $block->escapeHtml(__('User Role')) ?></span>
                    </label>
                    <div class="control">
                        <select data-role="role-select" name="role" id="role">
                            <?php foreach ($block->getRoles() as $role): ?>
                                <option value="<?= $block->escapeHtml($role->getId()) ?>">
                                    <?= $block->escapeHtml($role->getRoleName()) ?>
                                </option>
                                <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="field firstname required">
                    <label class="label" for="firstname">
                        <span><?= $block->escapeHtml(__('First Name')) ?></span>
                    </label>
                    <div class="control">
                        <input type="text" name="firstname" id="firstname" value="" title="<?= $block->escapeHtml(__('First Name')) ?>" class="input-text" data-validate="{required:true}" maxlength="50">
                    </div>
                </div>
                <div class="field lastname required">
                    <label class="label" for="lastname">
                        <span><?= $block->escapeHtml(__('Last Name')) ?></span>
                    </label>
                    <div class="control">
                        <input type="text" name="lastname" id="lastname" value="" title="<?= $block->escapeHtml(__('Last Name')) ?>" class="input-text" data-validate="{required:true}" maxlength="50">
                    </div>
                </div>
                <div class="field email required">
                    <label class="label" for="email">
                        <span><?= $block->escapeHtml(__('Email')) ?></span>
                    </label>
                    <div class="control">
                        <input type="email" name="email" id="email" value="" title="<?= $block->escapeHtml(__('Email')) ?>" data-role="email" data-url-validate="<?= $block->escapeUrl($block->getUrl('*/customer/check')) ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" maxlength="50">
                    </div>
                </div>
                <div class="field telephone required">
                    <label class="label" for="telephone">
                        <span><?= $block->escapeHtml(__('Mobile Number')) ?></span>
                    </label>

                    <select name="extension_attributes[company_attributes][country_code]" id="country_code" class="adduser-countrycode">
                        <option style="background-image:url('<?= $block->getViewFileUrl('images/countryFlag_AE.png'); ?>');" value="971" selected="selected">+971</option>
                        <option style="background-image:url('<?= $block->getViewFileUrl('images/countryFlag_KE.png'); ?>');" value="254">+254</option>
                    </select>

                    <div class="control adduser-countrynum">
                        <input type="number" name="extension_attributes[company_attributes][telephone]" id="telephone" value="" title="<?= $block->escapeHtml(__('Phone Number')) ?>" class="form-control mobilenumber" data-validate="{required:true, 'validate-number':true}"  maxlength="10">
                       <span style="color:#e02b27;" id="spnPhone"></span>
                    </div>
                </div>
                <div class="field status">
                    <label class="label" for="status">
                        <span><?= $block->escapeHtml(__('Status')) ?></span>
                    </label>
                    <div class="control">
                        <select data-role="status-select" name="extension_attributes[company_attributes][status]" id="status">
                            <option value="1">
                                <?= $block->escapeHtml(__('Active')) ?>
                            </option>
                            <option value="0">
                                <?= $block->escapeHtml(__('Inactive')) ?>
                            </option>
                        </select>
                    </div>
                </div>

            </fieldset>
            <div id="additional_fields_create" data-role="create-additional-fields" class="_hidden additional-fields">
                <?= $block->getChildHtml('customer_form_user_attributes_create') ?>
            </div>
            <div id="additional_fields_edit" data-role="edit-additional-fields" class="_hidden additional-fields">
                <?= $block->getChildHtml('customer_form_user_attributes_edit') ?>
            </div>
        </form>

        <script type="text/javascript">
            require(['jquery', 'jquery/ui'], function($) {
                jQuery().ready(function() {
                    $('body').click(function(e){
                        clickedonPopup = $(event.target).closest(".modal-inner-wrap").length;
                        if(!clickedonPopup){
                            $('#spnPhone').html('');
                        }
                    });
                    /* Custom select design */
                    jQuery('.field.telephone').append('<div class="button countryflag-code"></div>');
                    jQuery('.field.telephone').append('<ul class="select-list"></ul>');
                    jQuery('.field.telephone select option').each(function() {
                        var bg = jQuery(this).css('background-image');
                        jQuery('.select-list').append('<li class="clsAnchor"><span value="' + jQuery(this).val() + '" class="' + jQuery(this).attr('class') + '" style=background-image:' + bg + '>' + jQuery(this).text() + '</span></li>');
                    });
                    jQuery('.field.telephone .button').html('<span class="isd-code-flag" style=background-image:' + jQuery('.field.telephone select').find(':selected').css('background-image') + '>' + jQuery('.field.telephone select').find(':selected').text() + '</span>' + '<a href="javascript:void(0);" class="select-list-link">Arrow</a>');
                    jQuery('.field.telephone ul li').each(function() {
                        if (jQuery(this).find('span').text() == jQuery('.field.telephone select').find(':selected').text()) {
                            jQuery(this).addClass('active');
                        }
                    });
                    jQuery('.field.telephone .select-list span').on('click', function() {
                        var dd_text = jQuery(this).text();
                        var dd_img = jQuery(this).css('background-image');
                        var dd_val = jQuery(this).attr('value');
                        jQuery('.field.telephone .button').html('<span class="isd-code-flag" style=background-image:' + dd_img + '>' + dd_text + '</span>' + '<a href="javascript:void(0);" class="select-list-link">Arrow</a>');
                        jQuery('.field.telephone .select-list span').parent().removeClass('active');
                        jQuery(this).parent().addClass('active');
                        $('.field.telephone select#country_code').val(dd_val);
                        $('.field.telephone .select-list li').slideUp();
                        jQuery('.isd-code-flag').click(function() {
                            jQuery('.field.telephone ul li').slideToggle();
                        });
                    });
                    jQuery('.field.telephone .button').on('click', 'a.select-list-link', function() {
                        jQuery('.field.telephone ul li').slideToggle();
                    });
                    jQuery('.isd-code-flag').click(function() {
                        jQuery('.field.telephone ul li').slideToggle();
                    });

                     jQuery('#telephone').keypress((e)=>{
                        telephoneInputVal = $('#telephone').val();
                        if(telephoneInputVal.length >= 10 || e.keyCode == 45 || e.keyCode < 48 || e.keyCode > 57){
                            
                            return false;
                        }
                    });
                    
                    /* End */
                });

               
            });
        </script>
