<?php
/**
 * @author SpadeWorx Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Checkout
 */
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkoutSuccess-wrap">
	<div class="checkout-success">
		<?php if ($block->getOrderId()):?>
			<?= $block->getChildHtml('display-thankyou-message') ?>
			<div class="success-messages">
				<?php if ($block->getCanViewOrder()) :?>
				<div class="referencenum-txt"><p><strong><?= __('Your order reference number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></strong>
					<?= $block->getChildHtml('display-order-status') ?>
				</p></div>
					<?= $block->getChildHtml('display-sapnumber') ?>
				<?php  else :?>
					<p><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
				<?php endif;?>
				</div>
			<?= $block->getChildHtml('display-lponumber') ?>
			<?= $block->getChildHtml('display-order-documents') ?>
			<?= $block->getChildHtml('details') ?>
			<?= $block->getChildHtml('display-payment-documents') ?>
		<?php endif;?>

		<?= $block->getAdditionalInfoHtml() ?>
		<?= $block->getChildHtml('cms') ?>

		<div class="actions-toolbar">
			<div class="primary">
				<a class="action primary continue" href="<?= $block->getUrl() ?>"><span><?= __('Continue Shopping') ?></span></a>
			</div>
		</div>
	</div>
</div>
