<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$helper = $this->helper('Redington\Checkout\Helper\Data');
?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info */ ?>
<?php $_order = $block->getOrder() ?>

<div id="order-messages">
    <?= $block->getChildHtml('order_messages') ?>
</div>

<?= $block->getChildHtml('order_info') ?>
<input type="hidden" name="order_id" value="<?= /* @escapeNotVerified */ $_order->getId() ?>"/>

<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Payment &amp; Shipping Method') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method<?php if ($_order->getIsVirtual()): ?> order-payment-method-virtual<?php endif; ?>">
            <?php /* Payment Method */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @escapeNotVerified */ __('Payment Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="order-payment-method-title"><?= $block->getPaymentHtml() ?></div>
                <div class="order-payment-currency"><?= /* @escapeNotVerified */ __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?></div>
                <div class="order-payment-additional">
                    <?= $block->getChildHtml('order_payment_additional') ?>
                    <?= $block->getChildHtml('payment_additional_info') ?>
                    <?php 
                        $paymentRefdoc = '';
                        $paymentRefnumber = '';
                        $paymentMethod = $_order->getPayment()->getMethod();
                        $additionalData =  $helper->getOrderAdditionalInfo($_order->getQuoteId());
                        if($paymentMethod == 'cdc') :
                          $paymentRefdoc = $additionalData['cdc_document'] != "" ? $additionalData['cdc_document'] : '';
                          $paymentRefnumber = $additionalData['cdc_ref_no'] != "" ? $additionalData['cdc_ref_no'] : '';
                        endif;
                        if($paymentMethod == 'pdc') :
                            $paymentRefdoc = $additionalData['pdc_document'] != "" ? $additionalData['pdc_document'] : '';
                            $paymentRefnumber = $additionalData['pdc_ref_no'] != "" ? $additionalData['pdc_ref_no'] : '';
                        endif;  
                        
                        if($paymentMethod == 'cashpayment') :
                            $paymentRefdoc = $additionalData['cash_document'] != "" ? $additionalData['cash_document'] : '';
                            $paymentRefnumber = $additionalData['cash_ref_no'] != "" ? $additionalData['cash_ref_no'] : '';
                        endif;
                        

                    if($paymentRefdoc !='') :
                    ?>

                    <p><span class="document-label"><a href="<?php echo $paymentRefdoc;?>" target="_blank" ><?php echo __('Payment Reference Document')?></a></span></p>
                    <p><span class="document-label"><?php echo __('Payment Reference Number') ?> : <?php echo $paymentRefnumber;?></span></p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <?= $block->getChildHtml('order_shipping_view') ?>
    </div>
</section>

<?= $block->getChildHtml('order_additional_info') ?>

<?= $block->getGiftOptionsHtml() ?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Items Ordered') ?></span>
    </div>
    <?= $block->getItemsHtml() ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Order Total') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @escapeNotVerified */ __('Notes for this Order') ?></span>
            </div>
            <?= $block->getChildHtml('order_history') ?>
        </div>

        <div class="admin__page-section-item order-totals">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @escapeNotVerified */ __('Order Totals') ?></span>
            </div>
            <?= $block->getChildHtml('order_totals') ?>
        </div>
    </div>
</section>

<?= $block->getChildHtml('popup_window') ?>

<script>
require([
    "prototype",
    "Magento_Sales/order/giftoptions_tooltip"
], function(){

//<![CDATA[
    /**
     * Retrieve gift options tooltip content
     */
    function getGiftOptionsTooltipContent(itemId) {
        var contentLines = [];
        var headerLine = null;
        var contentLine = null;

        $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
            if (element.down(0)) {
                headerLine = element.down(0).innerHTML;
                contentLine = element.down(0).next().innerHTML;
                if (contentLine.length > 30) {
                    contentLine = contentLine.slice(0,30) + '...';
                }
                contentLines.push(headerLine + ' ' + contentLine);
            }
        });
        return contentLines.join('<br/>');
    }
    giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);
    window.getGiftOptionsTooltipContent = getGiftOptionsTooltipContent;
//]]>

});
</script>
