<?php

namespace Redington\AddressApproval\Helper;

class Region {

    const REGION_ARRAY = [
        "AE" => [
            "001" => "Abu Dhabi",
            "002" => "Ajman",
            "003" => "Al Ain",
            "008" => "Dubai",
            "009" => "Fujairah",
            "015" => "Ras al-Khaimah",
            "016" => "Umm al-Qaiwain",
            "018" => "Sharjah",
        ],
        "KE" => [
            "001" => "Nairobi",
            "002" => "Awendo",
            "003" => "Bungoma",
            "004" => "Busia",
            "005" => "Elburgon",
            "006" => "Eldama Ravine",
            "007" => "Eldoret",
            "008" => "Embu",
            "009" => "Garissa",
            "010" => "Gilgil",
            "011" => "Homa Bay",
            "012" => "Isiolo",
            "013" => "Kakamega",
            "014" => "Kapenguria",
            "015" => "Kapsabet",
            "016" => "Karuri",
            "017" => "Kehancha",
            "018" => "Kericho",
            "019" => "Kerugoya (/ Kutus)",
            "020" => "Kiambu",
            "021" => "Kilifi",
            "022" => "Kimilili",
            "023" => "Kisii",
            "024" => "Kisumu",
            "025" => "Kitale",
            "026" => "Kitui",
            "027" => "Lamu",
            "028" => "Lodwar",
            "029" => "Machakos",
            "030" => "Malindi",
            "031" => "Mandera",
            "032" => "Maragua",
            "033" => "Maralal",
            "034" => "Mariakani",
            "035" => "Marsabit",
            "036" => "Mavoko (Athi River)",
            "037" => "Meru",
            "038" => "Migori",
            "039" => "Molo",
            "040" => "Mombasa",
            "041" => "Moyale",
            "042" => "Muhoroni",
            "043" => "Mumias",
            "044" => "Murang'a",
            "045" => "Mwingi",
            "046" => "Naivasha",
            "047" => "Nakuru",
            "048" => "Nanyuki",
            "049" => "Narok",
            "050" => "Ngong",
            "051" => "Nyahururu",
            "052" => "Nyeri",
            "053" => "Ol Kalou",
            "054" => "Rongai",
            "055" => "Ruiru",
            "056" => "Siaya",
            "057" => "Taveta",
            "058" => "Thika",
            "059" => "Vihiga",
            "060" => "Voi",
            "061" => "Wajir",
            "062" => "Webuye",
            "063" => "Othaya",
            "064" => "Karatina",
            "065" => "Ruaraka",
            "066" => "Kikuyu",
            "067" => "Gatundo",
        ]
    ];
    public function getRegionData(){
        return self::REGION_ARRAY;
    }

}