<?php
/**
 * @author SpadeWorx Team
 * @copyright Copyright (c) 2019 Redington
 * @package Redington_Catalog
 */
$helper = $this->helper('Redington\Catalog\Helper\Data');
?>
<?php /* @var $block \Magento\ProductAlert\Block\Product\View */?>
<div class="product alert <?= $block->getHtmlClass() ?>">    
    <input type="text" name="emailid" value="<?= /* @noEscape */ $helper->getCustomerData('email');//$block->getCustomerEmail(); ?>" readonly="true" />
    <a href="#" data-post='<?= /* @noEscape */ $block->getPostAction() ?>'
       title="<?= $block->escapeHtml(__($block->getSignupLabel())) ?>" class="action alert">
        <?= $block->escapeHtml(__($block->getSignupLabel())) ?>
    </a>
</div>
