<?php

$items = $this->_getList();
 $image = 'recently_viewed_products_grid_content_widget';
$type = 'widget-viewed';
    $mode = 'grid';

    $type = $type . '-' . $mode;
?>
<div class="block widget block-viewed-products">
        <div class="block-title">
            <strong role="heading" aria-level="2">Recommended for you</strong>
        </div>
        <div class="block-content">
           
          
                <ul class="list-product-home product-items ">
                    <?php foreach ($items as $_item): ?>
                        <li class="product-item">
                            <div class="item collection-box">
                                <a href="<?= /* @escapeNotVerified */ $_item->getUrl() ?>" class="product-item-photo">
                                   <?= $block->getImage($_item, $image)->toHtml() ?> 
                                </a>
                                <div class="product-item-details">
                                    <strong class="product-item-name">
                                        <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                           href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product-item-link">
                                            <?= $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>
                                    <?php /* @escapeNotVerified */ echo $block->getProductPriceHtml(
                                        $_item,
                                        \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
                                        \Magento\Framework\Pricing\Render::ZONE_ITEM_LIST,
                                        [
                                            'price_id_suffix' => '-' . $type
                                        ]
                                    ) ?>
                                   
                                    
                                 
                                        <div class="product-item-actions">
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                            <button class="action tocart primary"
                                                                    data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}'
                                                                    type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php else: ?>
                                                            <?php
                                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                            ?>
                                                            <button class="action tocart primary btn-action btn-cart"
                                                                    data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                                    type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                         
                                        </div>
                                   
                                </div>
                            </div>
                        </li>
                    <?php endforeach ?>
                </ul>
            </div>
           
        </div>
    